# Dockerfile.test
FROM node:20

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# Set environment for test
ENV NODE_ENV=test

# Run tests by default
CMD ["npm", "test"]
